core/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.frontpage, name='home'),
    path('terms/', views.terms, name='terms'),
]

puracultura/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('pedido/', include('pedido.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

# Definimos el nombre de la aplicación, que se utilizará para referenciar estas URLs en otras partes del código
app_name = 'userprofile'

# Definimos las URLs de la aplicación
urlpatterns = [
    # La URL 'signup/' está asociada con la vista 'signup_view' y tiene el nombre 'signup'
    path('signup/', views.signup_view, name='signup'),
    # La URL 'login/' está asociada con la vista 'login_view' y tiene el nombre 'login'
    path('login/', views.login_view, name='login'),
    # La URL 'logout/' está asociada con la vista 'LogoutView' y tiene el nombre 'logout'
    # 'LogoutView.as_view(next_page='/')' crea una vista basada en clase que redirige al usuario a la página de inicio después de cerrar sesión
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('perfil/', views.perfil, name='perfil'),
    path('agregar_direccion/', views.agregar_direccion, name='agregar_direccion'),
    path('editar_direccion/<int:id>/', views.editar_direccion, name='editar_direccion'),
    path('eliminar_direccion/<int:id>/', views.eliminar_direccion, name='eliminar_direccion'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

# Definición de validadores personalizados para cédula y teléfono
validar_cedula = RegexValidator(regex='^[0-9]+$', message='La cédula debe contener solo números', code='cedula_invalida')
validar_telefono = RegexValidator(regex='^[0-9]+$', message='El teléfono debe contener solo números', code='telefono_invalido')

class Usuario(AbstractUser):
    # Modelo de usuario personalizado que hereda de AbstractUser
    vendedor = models.BooleanField(default=False)  # Campo booleano para indicar si el usuario es vendedor o no
    biografia = models.TextField(blank=True, null=True)  # Campo de texto para la biografía del usuario
    fecha_registro = models.DateTimeField(auto_now_add=True)  # Campo de fecha y hora para el registro del usuario
    cedula = models.CharField(max_length=9, unique=True, validators=[validar_cedula])  # Campo de texto para la cédula del usuario con validador personalizado
    telefono = models.CharField(max_length=15, unique=True, validators=[validar_telefono])  # Campo de texto para el teléfono del usuario con validador personalizado

class Direccion(models.Model):
    # Modelo de dirección asociado a un usuario
    usuario = models.ForeignKey(Usuario, related_name='direcciones', on_delete=models.CASCADE)  # Relación de clave foránea con el modelo Usuario
    direccion = models.CharField(max_length=255)  # Campo de texto para la dirección
    ciudad = models.CharField(max_length=100)  # Campo de texto para la ciudad
    pais = models.CharField(max_length=100)  # Campo de texto para el país
    codigo_postal = models.CharField(max_length=20)  # Campo de texto para el código postal

    def __str__(self):
        return f"{self.direccion}, {self.ciudad}, {self.pais}, {self.codigo_postal}"

userprofile/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Usuario, Direccion

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Usuario o correo electrónico', widget=forms.TextInput(attrs={
        'placeholder': 'Nombre de Usuario o Correo Electrónico',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={
        'placeholder': 'Contraseña',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))


class SignupForm(UserCreationForm):
    
    username = forms.CharField(label = 'Usuario', widget=forms.TextInput(attrs={
        'placeholder': 'Nombre de usuario',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    first_name = forms.CharField(label = 'Nombre', widget=forms.TextInput(attrs={
        'placeholder': 'Nombre',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }), required=True)
    last_name = forms.CharField(label = 'Apellidos', widget=forms.TextInput(attrs={
        'placeholder': 'Apellido',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }), required=True)
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Correo electrónico',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    password1 = forms.CharField(label = 'Contraseña', widget=forms.PasswordInput(attrs={
        'placeholder': 'Contraseña',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    password2 = forms.CharField(label = 'Repetir Contraseña', widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirmación de contraseña',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    vendedor = forms.BooleanField(label='Vendedor', required=False, widget=forms.CheckboxInput(attrs={
        'class': 'leading-tight'
    }))
    biografia = forms.CharField(label='Biografía', required=False, widget=forms.Textarea(attrs={
        'placeholder': 'Biografía',
        'class': 'w-full px-4 py-2 border rounded-xl',
        'rows': 3
    }))
    cedula = forms.CharField(label='Cédula', max_length=9, widget=forms.TextInput(attrs={
        'placeholder': 'Cédula',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    telefono = forms.CharField(label='Teléfono', max_length=15, widget=forms.TextInput(attrs={
        'placeholder': 'Teléfono',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    direccion = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Dirección',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    ciudad = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ciudad',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    pais = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'País',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    codigo_postal = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Código Postal',
        'class': 'w-full px-4 py-2 border rounded-xl'
    }))
    
     # Aquí definimos los metadatos del formulario
    class Meta:
        model = Usuario
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2',
                  'vendedor', 'biografia', 'cedula', 'telefono', 'direccion', 'ciudad', 'pais', 'codigo_postal']

    # Redefinimos el método save para guardar los datos del formulario en el modelo
    def save(self, commit=True):
        user = super().save(commit=False)  # Creamos un nuevo usuario pero no lo guardamos en la base de datos todavía
        # Asignamos los datos del formulario al usuario
        user.vendedor = self.cleaned_data.get('vendedor')
        user.biografia = self.cleaned_data.get('biografia')
        user.cedula = self.cleaned_data.get('cedula')
        user.telefono = self.cleaned_data.get('telefono')
        if commit:  # Si commit es True, guardamos el usuario en la base de datos
            user.save()
            # Creamos una nueva dirección para el usuario con los datos del formulario
            Direccion.objects.create(
                usuario=user,
                direccion=self.cleaned_data.get('direccion'),
                ciudad=self.cleaned_data.get('ciudad'),
                pais=self.cleaned_data.get('pais'),
                codigo_postal=self.cleaned_data.get('codigo_postal')
            )
        return user  # Devolvemos el usuario creado
    
class UsuarioForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        vendedor = self.instance.vendedor if self.instance else False
        if not vendedor:
            del self.fields['biografia']

    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'email', 'biografia', 'telefono']
        labels = {
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'email': 'Correo electrónico',
            'biografia': 'Biografía',
            'telefono': 'Teléfono',
        }
    
        
class DireccionForm(forms.ModelForm):
    class Meta:
        model = Direccion
        fields = ['direccion', 'ciudad', 'pais', 'codigo_postal']

userprofile/views.py
# Importamos los módulos necesarios de Django
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from .models import Direccion
from .forms import LoginForm, SignupForm, UsuarioForm, DireccionForm  # Importamos los formularios que hemos definido

# Definimos la vista para el registro de usuarios
def signup_view(request):
    # Si el usuario ya está autenticado, lo redirigimos a la página de inicio
    if request.user.is_authenticated:
        return redirect('core:home')  
    # Si el método de la petición es POST, procesamos el formulario
    if request.method == 'POST':
        form = SignupForm(request.POST)  # Creamos un formulario con los datos de la petición
        # Si el formulario es válido, lo guardamos y redirigimos al usuario a la página de inicio de sesión
        if form.is_valid():
            form.save()
            return redirect('userprofile:login')
    # Si el método de la petición no es POST, mostramos el formulario vacío
    else:
        form = SignupForm()
    # Renderizamos la plantilla de registro con el formulario
    return render(request, 'userprofile/signup.html', {'form': form})

# Definimos la vista para el inicio de sesión de usuarios
def login_view(request):
    # Si el usuario ya está autenticado, lo redirigimos a la página de inicio
    if request.user.is_authenticated:
        return redirect('core:home')  
    # Si el método de la petición es POST, procesamos el formulario
    if request.method == 'POST':
        form = LoginForm(data=request.POST)  # Creamos un formulario con los datos de la petición
        # Si el formulario es válido, autenticamos al usuario
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            # Si el usuario es autenticado con éxito, iniciamos su sesión y lo redirigimos a la página de inicio
            if user is not None:
                login(request, user)
                return redirect('core:home')
    # Si el método de la petición no es POST, mostramos el formulario vacío
    else:
        form = LoginForm()
    # Renderizamos la plantilla de inicio de sesión con el formulario
    return render(request, 'userprofile/login.html', {'form': form})

@login_required
def perfil(request):
    if request.method == 'POST':
        user_form = UsuarioForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            return redirect('userprofile:perfil')
    else:
        user_form = UsuarioForm(instance=request.user)

    direcciones = Direccion.objects.filter(usuario=request.user)
    direccion_form = DireccionForm()
    return render(request, 'userprofile/perfil.html', {
        'user_form': user_form,
        'direccion_form': direccion_form,
        'direcciones': direcciones
    })
    
@login_required    
def agregar_direccion(request):
    if request.method == 'POST':
        direccion_form = DireccionForm(request.POST)
        if direccion_form.is_valid():
            direccion = direccion_form.save(commit=False)
            direccion.usuario = request.user
            direccion.save()
            return redirect('userprofile:perfil')
    return redirect('userprofile:perfil')

@login_required    
def editar_direccion(request, id):
    direccion = get_object_or_404(Direccion, id=id, usuario=request.user)
    if request.method == 'POST':
        direccion_form = DireccionForm(request.POST, instance=direccion)
        if direccion_form.is_valid():
            direccion_form.save()
            return redirect('userprofile:perfil')
    else:
        direccion_form = DireccionForm(instance=direccion)
    return render(request, 'userprofile/editar_direccion.html', {
        'direccion_form': direccion_form,
        'direccion': direccion
    })


@login_required    
def eliminar_direccion(request, id):
    direccion = Direccion.objects.get(id=id)
    direccion.delete()
    return redirect('userprofile:perfil')

userprofile/templates/userprofile/editar_direccion.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mx-auto p-6">
    <h2 class="text-2xl font-bold mb-4">Editar Dirección</h2>
    <form method="post" action="{% url 'userprofile:editar_direccion' direccion.id %}">
        {% csrf_token %}
        <div class="grid grid-cols-1 gap-6">
            {{ direccion_form| crispy }}
        </div>
        <div class="flex justify-end mt-4">
            <a href="{% url 'userprofile:perfil' %}" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded mr-2">Cancelar</a>
            <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Guardar Cambios</button>
        </div>
    </form>
</div>
{% endblock %}

userprofile/templates/userprofile/login.html
{% extends "core/base.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-full max-w-md mx-auto mt-6 p-8 border border-gray-300 rounded-lg shadow-lg bg-slate-800">
    <h1 class="text-2xl text-center font-bold mb-8 text-white">Log in</h1>

    <form method="post" action="." id="loginForm">
        {% csrf_token %}
        
        <div class="mb-4" id="username_div">
            {{ form.username.errors.as_ul }}
            <label for="{{ form.username.id_for_label }}" class="block text-sm font-bold mb-2 text-white">{{ form.username.label }}</label>
            <input type="text" name="username" id="{{ form.username.id_for_label }}" required class="{{ form.username.field.widget.attrs.class }}" placeholder="{{ form.username.field.widget.attrs.placeholder }}">
        </div>        
        
        <div class="mb-4" id="password_div">
            {{ form.password.errors.as_ul }}
            <label for="{{ form.password.id_for_label }}" class="block text-sm font-bold mb-2 text-white">{{ form.password.label }}</label>
            <input type="password" name="password" id="{{ form.password.id_for_label }}" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" required class="{{ form.password.field.widget.attrs.class }}" placeholder="{{ form.password.field.widget.attrs.placeholder }}">
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button type="submit" class="w-full py-2 px-4 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg">Submit</button>
        <p class="text-center mt-4 text-white">¿No tienes una cuenta? <a href="{% url 'userprofile:signup' %}" class="text-blue-500">Crear cuenta</a></p>
    </form>
</div>

{% endblock %}

userprofile/templates/userprofile/perfil.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Perfil{% endblock %}

{% block content %}
<div class="container mx-auto p-6">
    <h2 class="text-2xl font-bold mb-4">Editar Perfil</h2>
    <form method="post" class="mb-6">
        {% csrf_token %}
        <div class="grid grid-cols-1 gap-6">
            {{ user_form.first_name|as_crispy_field }}
            {{ user_form.last_name|as_crispy_field }}
            {{ user_form.email|as_crispy_field }}
            {% if user_form.biografia %}
                {{ user_form.biografia|as_crispy_field }}
            {% endif %}
            {{ user_form.telefono|as_crispy_field }}
        </div>
        <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Guardar Cambios</button>
    </form>
    
 {%if not request.user.vendedor %}   
    <h2 class="text-2xl font-bold mb-4">Mis Direcciones</h2>
    <form method="post" action="{% url 'userprofile:agregar_direccion' %}" class="mb-6">
        {% csrf_token %}
        <div class="grid grid-cols-1 gap-6">
            {{ direccion_form|crispy }}
        </div>
        <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Agregar Dirección</button>
    </form>

    <div>
        {% for direccion in direcciones %}
            <div class="flex justify-between items-center bg-white p-4 rounded-lg shadow mb-4">
                <div>
                    <p>{{ direccion.direccion }}, {{ direccion.ciudad }}, {{ direccion.pais }}</p>
                    <p class="text-gray-600">Código Postal: {{ direccion.codigo_postal }}</p>
                </div>
                <div class="flex gap-4">
                    <a href="{% url 'userprofile:editar_direccion' direccion.id %}" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded">Editar</a>
                    <a href="{% url 'userprofile:eliminar_direccion' direccion.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Eliminar</a>
                </div>
            </div>
        {% empty %}
            <p>No hay direcciones agregadas.</p>
        {% endfor %}
    </div>
{% endif %}
</div>
{% endblock %}

userprofile/templates/userprofile/signup.html
{% extends "core/base.html" %}

{% block title %}Registrar{% endblock %}

{% block content %}
<div class="w-full max-w-md mx-auto mt-6 p-8 border border-gray-300 rounded-lg shadow-lg bg-slate-800">
    <h1 class="text-2xl text-center font-bold mb-8 text-white">Registrar</h1>

    <form method="post" action="." id="signupForm">
        {% csrf_token %}
        
        {% for field in form %}
            <div class="mb-4" id="{{ field.name }}_div">
                {{ field.errors.as_ul }}
                <label for="{{ field.id_for_label }}" class="block text-sm font-bold mb-2 text-white">{{ field.label }}</label>
                
                {% if field.name == 'vendedor' %}
                    <input type="checkbox" name="{{ field.name }}" id="{{ field.id_for_label }}" {% if field.value %}checked{% endif %}>
                    <label for="{{ field.id_for_label }}" class="text-white">{{ field.label }}</label><br>
                {% else %}
                    {{ field }}
                {% endif %}
            </div>
        {% endfor %}
        
        <button type="submit" class="w-full py-2 px-4 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg">Registrar</button>
    </form>
</div>

<script>
    const bioDiv = document.getElementById("biografia_div");
    bioDiv.style.display = "none";
    bioDiv.style.transition = "opacity 0.5s ease";

    document.getElementById('{{ form.vendedor.id_for_label }}').addEventListener('change', function() {
        if (this.checked) {
            bioDiv.style.display = "block";
            setTimeout(() => bioDiv.style.opacity = "1", 300); 
        } else {
            bioDiv.style.opacity = "0";
            setTimeout(() => bioDiv.style.display = "none", 500); 
        }
    });
</script>
{% endblock %}