core/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.frontpage, name='home'),
    path('terms/', views.terms, name='terms'),
]

item/urls.py
from django.urls import path

from . import views

# Definimos el nombre de la aplicación, que se usará para hacer referencia a estas URLs desde otras partes de Django
app_name = 'item'

# Definimos las URLs para esta aplicación
urlpatterns = [
    # La URL 'new/' está asociada con la vista 'new'. Esto significa que cuando un usuario visita 'item/new/', Django ejecutará la función de vista 'new'.
    path('new/', views.new, name='new'),
    path('add-to-cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('increase-quantity/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease-quantity/<int:item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('cart/', views.cart_view, name='cart_view'),
    # La URL '<int:pk>/' está asociada con la vista 'detail'. Esto significa que cuando un usuario visita 'item/1/', por ejemplo, Django ejecutará la función de vista 'detail' con 'pk' igual a 1.
    path('<int:pk>/', views.detail, name='detail'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('<int:pk>/edit/', views.edit_item, name='edit'),
    path('<int:pk>/delete/', views.delete_item, name='delete'),
    path('search/', views.search, name='search'),
    path('category/<int:pk>/', views.category_detail, name='category_detail'),
    
]

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'  

urlpatterns = [
    path('resumen/', views.resumen_pedido, name='resumen_pedido'),
    path('confirmar/', views.confirmar_compra, name='confirmar_compra'),
    path('cancelar/', views.cancelar_compra, name='cancelar_compra'),
    path('historial_vendedor/', views.historial_pedidos_vendedor, name='historial_pedidos_vendedor'),
    path('historial/', views.historial_pedidos, name='historial_pedidos'),
    path('actualizar/<int:pedido_id>/', views.actualizar_estado_pedido, name='actualizar_estado'),
    
]

puracultura/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('pedido/', include('pedido.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

# Definimos el nombre de la aplicación, que se utilizará para referenciar estas URLs en otras partes del código
app_name = 'userprofile'

# Definimos las URLs de la aplicación
urlpatterns = [
    # La URL 'signup/' está asociada con la vista 'signup_view' y tiene el nombre 'signup'
    path('signup/', views.signup_view, name='signup'),
    # La URL 'login/' está asociada con la vista 'login_view' y tiene el nombre 'login'
    path('login/', views.login_view, name='login'),
    # La URL 'logout/' está asociada con la vista 'LogoutView' y tiene el nombre 'logout'
    # 'LogoutView.as_view(next_page='/')' crea una vista basada en clase que redirige al usuario a la página de inicio después de cerrar sesión
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('perfil/', views.perfil, name='perfil'),
    path('agregar_direccion/', views.agregar_direccion, name='agregar_direccion'),
    path('editar_direccion/<int:id>/', views.editar_direccion, name='editar_direccion'),
    path('eliminar_direccion/<int:id>/', views.eliminar_direccion, name='eliminar_direccion'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.db.models import Count, Q
from django.shortcuts import render
from item.models import Category, Item

def frontpage(request):
    items = Item.objects.filter(stock__gt=0).order_by('-created_at')[:6]
    categories = Category.objects.annotate(
        num_items_in_stock=Count('items', filter=Q(items__stock__gt=0))
    ).filter(num_items_in_stock__gt=0)
    
    return render(request, 'core/frontpage.html',{
        'categories': categories,
        'items': items,
    })

def terms(request):
    return render(request, 'core/terms.html')

core/templates/core/base.html
{%load static%}
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %} {% endblock %} | PuraCultura</title>
    </head>

    <body> 
            <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
                <a href="/">
                    <img src="{% static 'logo_images/PuraCulturaLogo1.jpg' %}" alt="PuraCultura Logo" class="w-64 h-auto">
                </a> 
            <div class="flex-grow mx-4 max-w-xl">
                <form action="{% url 'item:search' %}" method="get">
                    <div class="relative flex w-full items-stretch">
                        <input type="search" name="query" class="relative flex-auto appearance-none rounded-l-full border border-r-0 border-neutral-300 px-4 py-2 leading-[1.6] transition duration-200 ease-in-out focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" placeholder="Buscar" aria-label="Buscar">
                        <button class="flex items-center justify-center rounded-r-full border border-l-0 border-neutral-300 px-4 py-2 text-neutral-700 transition duration-200 ease-in-out focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" type="submit" id="button-addon2">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="h-5 w-5">
                                <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
                            </svg>
                        </button>
                    </div>
                </form>
            </div>
            
            <div class="flex space-x-4 items-center">
                {% if request.user.is_authenticated %}
                    {% if request.user.vendedor %}
                        <a href="{% url 'item:dashboard' %}" class="text-lg font-semibold hover:text-gray-500">Mis Productos</a>
                        <a href="{% url 'pedido:historial_pedidos_vendedor' %}" class="text-lg font-semibold hover:text-gray-500">Pedidos</a>
                        <a href="{% url 'userprofile:perfil' %}" class="text-lg font-semibold hover:text-gray-500">Perfil</a>
                        <a href="{% url 'userprofile:logout' %}" class="text-lg font-semibold hover:text-gray-500">Log out</a>
                    {% else %}
                        <a href="{% url 'item:cart_view' %}" class="relative text-lg font-semibold hover:text-gray-500 flex items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-bag-fill" viewBox="0 0 16 16">
                                <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4z"/>
                            </svg>
                            {% if cart_item_count >= 1 %}
                                <span class="absolute top-0 right-0 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-white transform translate-x-1/2 -translate-y-1/2 bg-red-600 rounded-full">
                                    {{ cart_item_count }}
                                </span>
                            {% endif %}
                        </a>    
                        <a href="{% url 'userprofile:perfil' %}" class="text-lg font-semibold hover:text-gray-500">Perfil</a>
                        <a href="{% url 'pedido:historial_pedidos' %}" class="text-lg font-semibold hover:text-gray-500">Pedidos</a>                    
                        <a href="{% url 'userprofile:logout' %}" class="text-lg font-semibold hover:text-gray-500">Log out</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'userprofile:signup' %}" class="px-6 py-3 text-lg font-semibold bg-slate-700 text-white rounded-xl hover:bg-slate-500">Registro</a>
                    <a href="{% url 'userprofile:login' %}" class="px-6 py-3 text-lg font-semibold bg-slate-700 text-white rounded-xl hover:bg-slate-500">Log in</a>
                {% endif %}
        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-s/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">Acerca de</h3>

                <p class="text-lg text-gray-500">PuraCultura es un mercado digital dedicado a resaltar la rica tradición y habilidad de artistas y artesanos costarricenses. Nuestra misión es brindar una plataforma donde el talento tico pueda brillar y donde los apasionados de arte y artesanía puedan descubrir y adquirir piezas genuinas, reflejo de nuestra cultura y raíces. Celebramos la esencia, creatividad y el espíritu emprendedor de cada artista costarricense que se une a nuestra comunidad. </p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'core:terms' %}" class="text-lg text-teal-500 hover:text-teal-700">Terminos y condiciones </a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %} Pagina Principal {% endblock %}

{% block content %}
   <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Productos Nuevos</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href= "{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" alt="item" class="w-full h-80 object-cover rounded-xl">
                        </div>

                        <div class="p-6 bg-white rounded-xl">
                            <h2 class="mb-2 text-2xl">{{ item.name }}</h2>
                            <p class="mb-2 text-gray-600">{{ item.description }}</p>
                            <p class="text-gray-900 font-bold">Precio: {{ item.price }} $</p>
                        </div>
            
                    </a> 
                </div>
            {% endfor %}
        </div>
   </div>

   <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categorías</h2>

    <div class="grid grid-cols-3 gap-2">
        {% for category in categories %}
            <div>
                <a href="{% url 'item:category_detail' category.id %}">
                    <div class="p-6 bg-white rounded-xl">
                        <h2 class="mb-2 text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-900 font-bold">{{ category.items.count }} {% if category.items.count == 1 %}producto{% else %}productos{% endif %}</p>
                    </div>
                </a> 
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

core/templates/core/terms.html
{% extends 'core/base.html' %}

{% block title %}Términos y Condiciones{% endblock %}

{% block content %}
<div class="container mx-auto mt-10 mb-10">
    <h2 class="text-3xl font-semibold mb-5">Términos y Condiciones</h2>
    <div class="bg-white shadow-md rounded my-6 p-6">
        <h3 class="text-xl font-semibold mb-3">Cuentas y registro</h3>
        <p>Para realizar pedidos en nuestra tienda se requiere crear una cuenta proporcionando información precisa y completa. Usted es responsable de mantener la confidencialidad de su cuenta y contraseña.</p>

        <h3 class="text-xl font-semibold mb-3">Descripción de los productos</h3>
        <p>Los productos están descritos con la mayor precisión posible. No obstante, no podemos garantizar que todos los detalles sean exactos, completos o libres de errores.</p>

        <h3 class="text-xl font-semibold mb-3">Pedidos y pagos</h3>
        <p>Al realizar un pedido, usted se compromete a pagar la cantidad total indicada en el momento de la compra. Todos los pagos son a través de métodos seguros y verificados.</p>

        <h3 class="text-xl font-semibold mb-3">Envíos</h3>
        <p>Los productos comprados serán enviados según la dirección que usted proporcione. Los tiempos de entrega dependen de cada vendedor.</p>

        <h3 class="text-xl font-semibold mb-3">Devoluciones</h3>
        <p>Si no está satisfecho con su compra, puede devolverla en un plazo de 15 días para obtener un reembolso completo o un cambio, sujeto a ciertas condiciones.</p>

        <h3 class="text-xl font-semibold mb-3">Propiedad intelectual</h3>
        <p>El contenido de la tienda, incluyendo textos, gráficos y logos, es propiedad de Puracultura y está protegido por leyes de propiedad intelectual.</p>

        <h3 class="text-xl font-semibold mb-3">Limitación de responsabilidad</h3>
        <p>Puracultura no será responsable de ningún daño que surja del uso de esta tienda en línea.</p>

        <h3 class="text-xl font-semibold mb-3">Cambios en los términos</h3>
        <p>Nos reservamos el derecho de realizar cambios en los términos y condiciones en cualquier momento. Su uso continuado de la tienda constituirá su aceptación de tales cambios.</p>

        <h3 class="text-xl font-semibold mb-3">Contacto</h3>
        <p>Para cualquier pregunta relacionada con estos términos, por favor contáctenos en: <a href="mailto:admin@puracultura.com" class="text-blue-500">admin@puracultura.com</a>.</p>
    </div>
</div>
{% endblock %}