core/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.frontpage, name='home'),
    path('terms/', views.terms, name='terms'),
]

item/urls.py
from django.urls import path

from . import views

# Definimos el nombre de la aplicación, que se usará para hacer referencia a estas URLs desde otras partes de Django
app_name = 'item'

# Definimos las URLs para esta aplicación
urlpatterns = [
    # La URL 'new/' está asociada con la vista 'new'. Esto significa que cuando un usuario visita 'item/new/', Django ejecutará la función de vista 'new'.
    path('new/', views.new, name='new'),
    path('add-to-cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('increase-quantity/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease-quantity/<int:item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('cart/', views.cart_view, name='cart_view'),
    # La URL '<int:pk>/' está asociada con la vista 'detail'. Esto significa que cuando un usuario visita 'item/1/', por ejemplo, Django ejecutará la función de vista 'detail' con 'pk' igual a 1.
    path('<int:pk>/', views.detail, name='detail'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('<int:pk>/edit/', views.edit_item, name='edit'),
    path('<int:pk>/delete/', views.delete_item, name='delete'),
    path('search/', views.search, name='search'),
    path('category/<int:pk>/', views.category_detail, name='category_detail'),
    
]

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'  

urlpatterns = [
    path('resumen/', views.resumen_pedido, name='resumen_pedido'),
    path('confirmar/', views.confirmar_compra, name='confirmar_compra'),
    path('cancelar/', views.cancelar_compra, name='cancelar_compra'),
    path('historial_vendedor/', views.historial_pedidos_vendedor, name='historial_pedidos_vendedor'),
    path('historial/', views.historial_pedidos, name='historial_pedidos'),
    path('actualizar/<int:pedido_id>/', views.actualizar_estado_pedido, name='actualizar_estado'),
    
]

puracultura/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('pedido/', include('pedido.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
# Importamos los módulos necesarios de Django
from django.db import models
from django.conf import settings

# Definimos el modelo Category
class Category(models.Model):
    # Cada categoría tiene un nombre
    name = models.CharField(max_length=255, verbose_name='Nombre')
    
    class Meta:
        # Las categorías se ordenan por su nombre
        ordering = ('name',)
        # El nombre plural en español para el modelo es 'Categorías'
        verbose_name_plural = 'Categorías'
        
    # La representación en cadena de una categoría es su nombre
    def __str__(self):
        return self.name
    
# Definimos el modelo Item
class Item(models.Model):
    # Cada item pertenece a una categoría
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE, verbose_name='Categoría')
    # Cada item tiene un nombre, descripción, precio, imagen, creador, fecha de creación y stock
    name = models.CharField(max_length=255, verbose_name='Nombre')
    description = models.TextField(blank=True, null=True, verbose_name='Descripción')
    price = models.FloatField(verbose_name='Precio')
    image = models.ImageField(upload_to='item_images', blank=True, null=True, verbose_name='Imagen')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='items', on_delete=models.CASCADE, verbose_name='Creado por')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creado en')
    stock = models.PositiveIntegerField(default=1, verbose_name='Inventario')
    
    # Propiedad que indica si el item está vendido (si el stock es 0)
    @property
    def is_sold(self):
        return self.stock == 0
    
    class Meta:
        # Los items se ordenan por su nombre
        ordering = ('name',)  
        
    # La representación en cadena de un item es su nombre
    def __str__(self):
        return self.name

# Definimos el modelo Review
class Review(models.Model):
    # Las opciones de calificación para una revisión
    RATING_CHOICES = (
        (1, "★☆☆☆☆"),
        (2, "★★☆☆☆"),
        (3, "★★★☆☆"),
        (4, "★★★★☆"),
        (5, "★★★★★"),
    )

    # Cada revisión pertenece a un item y tiene un autor, contenido, calificación y fecha de creación
    item = models.ForeignKey('Item', related_name='reviews', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='reviews', on_delete=models.CASCADE)
    content = models.TextField()
    rating = models.IntegerField(choices=RATING_CHOICES, default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    # La representación en cadena de una revisión es 'Review by {author} for {item}'
    def __str__(self):
        return f'Review by {self.author.username} for {self.item.name}'

item/forms.py
# Importamos el módulo forms de Django
from django import forms

# Importamos el modelo Item de nuestro módulo models
from .models import Item, Review

# Definimos una nueva forma llamada NewItemForm que hereda de forms.ModelForm
class NewItemForm(forms.ModelForm):
    # Dentro de la clase definimos una subclase Meta
    class Meta:
        # Especificamos que el modelo a utilizar es Item
        model = Item
        # Definimos los campos del modelo que queremos incluir en el formulario
        fields = ('name', 'description', 'price', 'category', 'stock', 'image')
        # Definimos los widgets para los campos del formulario. Esto nos permite personalizar cómo se renderizan los campos.
        widgets = {
            # Para el campo 'name', usamos un TextInput y establecemos el atributo 'placeholder' a 'Nombre'
            'name': forms.TextInput(attrs={'placeholder': 'Nombre'}),
            # Para el campo 'description', usamos un Textarea y establecemos el atributo 'placeholder' a 'Descripción'
            'description': forms.Textarea(attrs={'placeholder': 'Descripción'}),
            # Para el campo 'price', usamos un NumberInput y establecemos el atributo 'placeholder' a 'Precio'
            'price': forms.NumberInput(attrs={'placeholder': 'Precio'}),
            # Para el campo 'category', usamos un Select y establecemos el atributo 'placeholder' a 'Categoría'
            'category': forms.Select(attrs={'placeholder': 'Categoría'}),
            # Para el campo 'image', usamos un ClearableFileInput y establecemos el atributo 'placeholder' a 'Imagen'
            'image': forms.ClearableFileInput(attrs={'placeholder': 'Imagen'}),
            # Para el campo 'stock', usamos un NumberInput y establecemos el atributo 'placeholder' a 'Inventario'
            'stock': forms.NumberInput(attrs={'placeholder': 'Inventario'}),
        }
        

item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Q, F
from .cart import Cart
from .forms import NewItemForm
from .models import Item, Category

from django.core.paginator import Paginator


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, stock__gt=0).exclude(pk=pk)[:3]
    
    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def new(request):
    if not request.user.vendedor:
        return redirect('core:home') 

    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()
    
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Nuevo Producto',
    })


@login_required
def dashboard(request):
    if not request.user.vendedor:
        return redirect('core:home')

    items = Item.objects.filter(created_by=request.user)
    return render(request, 'item/dashboard.html', {'items': items})


@login_required
def edit_item(request, pk):
    if not request.user.vendedor:
        return redirect('core:home')

    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.pk)
    else:
        form = NewItemForm(instance=item)
    
    return render(request, 'item/edit_item.html', {
        'form': form,
        'title': 'Editar Producto',
        'item': item,  
    })

@login_required
def delete_item(request, pk):
    if not request.user.vendedor:
        return redirect('core:home')

    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        item.delete()
        return redirect('item:dashboard')  
    return render(request, 'item/delete_confirm.html', {
        'item': item
    })

def search(request):
    query = request.GET.get('query', '')
    sort_option = request.GET.get('sort', '')

    items = Item.objects.filter(Q(name__icontains=query) | Q(description__icontains=query), stock__gt=0)

    if sort_option == 'asc':
        items = items.order_by('price')
    elif sort_option == 'desc':
        items = items.order_by(F('price').desc())

    paginator = Paginator(items, 10)

    page_number = request.GET.get('page')
    item = paginator.get_page(page_number)

    return render(request, 'item/search.html', {
        'query': query,
        'item': item
    })

    
def category_detail(request, pk): 
    category = get_object_or_404(Category, pk=pk)
    items = Item.objects.filter(category=category, stock__gt=0) 
    
    paginator = Paginator(items, 10)

    page_number = request.GET.get('page')
    items = paginator.get_page(page_number)
    
    return render(request, 'item/category_detail.html', {
        'category': category,
        'items': items
    })

@login_required   
def add_to_cart(request, item_id):
    cart = Cart(request)
    cart.add(item_id)

    return redirect('item:cart_view')

@login_required
def remove_from_cart(request, item_id):
    cart = Cart(request)
    cart.remove(item_id)

    return redirect('item:cart_view')
@login_required
def cart_view(request):
    cart = Cart(request)

    return render(request, 'item/cart_view.html', {
        'cart': cart
    })
    
@login_required
def increase_quantity(request, item_id):
    cart = Cart(request)
    cart.add(item_id, quantity=1)  
    return redirect('item:cart_view')

@login_required
def decrease_quantity(request, item_id):
    cart = Cart(request)
    cart.add(item_id, quantity=-1) 
    return redirect('item:cart_view')
    

item/templates/item/cart_view.html
{% extends 'core/base.html' %}

{% block title %}Carrito{% endblock %}

{% block content %}
<div class="container mx-auto p-6">
    <h1 class="text-3xl font-semibold text-center mb-6">Carrito</h1>

    <div class="space-y-4">
        {% for item in cart %}
            <div class="flex justify-between items-center border-b-2 border-gray-100 py-4">
                <div>
                    <h2 class="text-xl font-bold">{{ item.product.name }}</h2> 
                    <p class="text-gray-600">Cantidad: {{ item.quantity }}</p>
                </div>
                <div class="text-right">
                    <p class="text-gray-900 font-bold">{{ item.product.price }} $</p>
                    <a href="{% url 'item:remove_from_cart' item.product.id %}" class="text-sm text-red-600 hover:text-red-800">Remover</a>
                </div>
            </div>
            <div>
                <a href="{% url 'item:increase_quantity' item.product.id %}" class="px-2 py-1 bg-blue-500 rounded text-white">+</a>
                {% if item.quantity > 1 %}
                    <a href="{% url 'item:decrease_quantity' item.product.id %}" class="px-2 py-1 bg-red-500 rounded text-white">-</a>
                {% endif %}
            </div>
        {% empty %}
            <p class="text-center text-gray-600">Tu carrito está vacío.</p>
        {% endfor %}
    </div>

    {% if cart %}
        <div class="text-right mt-6">
            <strong class="text-xl font-bold">Precio total + IVA: {{ cart.get_total_cost }} $</strong>
        </div>
        <a href="{% url 'pedido:resumen_pedido' %}" class="px-4 rounded py-2 bg-teal-600 text-white mt-4">Comprar</a>
    {% endif %}
</div>
{% endblock %}

item/templates/item/category_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <h1 class="text-2xl">{{ category.name }}</h1>

    <div class="flex flex-wrap gap-2">
        {% if items %}
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" alt="item" class="w-full h-80 object-cover rounded-xl">
                        </div>

                        <div class="p-6 bg-white rounded-xl">
                            <h2 class="mb-2 text-2xl">{{ item.name }}</h2>
                            <p class="mb-2 text-gray-600">{{ item.description }}</p>
                            <p class="text-gray-900 font-bold">Precio: {{ item.price }} $</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <div class="w-full p-2">
                <p class="text-xl text-slate-800">No hay productos en esta categoría.</p>
            </div>
        {% endif %}
        {% if items.has_other_pages %}
            <div class="pagination">
                {% if items.has_previous %}
                    <a href="?page={{ items.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current-page">{{ items.number }}</span>

                {% if items.has_next %}
                    <a href="?page={{ items.next_page_number }}">next</a>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

item/templates/item/dashboard.html
{% extends 'core/base.html' %}

{% block title %}Mis Productos{% endblock %}

{% block content %}
<div class="container mx-auto px-6 py-8">
    <h1 class="text-2xl font-bold mb-4 text-center">Mis Productos</h1>
    <a href="{% url 'item:new' %}" class="bg-teal-600 hover:bg-teal-800 text-white font-bold py-2 px-4 rounded">Agregar producto</a>

    {% if items %}
        <div class="mt-6">
            {% for item in items %}
            <div class="flex justify-between p-4 mb-4 bg-white rounded shadow">
                <div>{{ item.name }}</div>
                <div>
                    <a href="{% url 'item:edit' pk=item.pk %}" class="text-sm bg-orange-500 hover:bg-yellow-700 text-white py-1 px-2 rounded">Editar</a>
                    <a href="{% url 'item:delete' pk=item.pk %}" class="text-sm bg-red-600 hover:bg-red-700 text-white py-1 px-2 rounded">Borrar</a>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="mt-4">No tienes productos empieza por agregar uno.</p>
    {% endif %}
</div>
{% endblock %}

item/templates/item/delete_confirm.html
{% extends 'core/base.html' %}

{% block title %}Confirmación de borrado{% endblock %}

{% block content %}
<div class="container mx-auto px-6 py-8">
    <h1 class="text-xl font-bold text-slate-900 mb-4 text-center">Estás seguro de borrar este producto: "{{ item.name }}"?</h1>
    <div class="flex justify-center gap-4">
        <a href="{% url 'item:dashboard' %}" class="inline-block bg-gray-300 hover:bg-gray-400 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline transition-colors duration-150">Cancelar</a>
        <form method="post" action="#" class="inline-block">
            {% csrf_token %}
            <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline transition-colors duration-150">Borrar</button>
        </form>
    </div>
</div>
{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="w-full rounded-xl"> 
    </div>

    <div class="col-span-2 p-6 bg-slate-200 rounded-xl">
        <h1 class="text-3xl font-bold mb-4">{{ item.name }}</h1>
        <p class="text-slate-600 mb-2"><strong>Precio: </strong> {{ item.price }}$</p>
        <p class="text-slate-600 mb-2"><strong>Seller: </strong> {{ item.created_by.username }}</p>

        {% if item.description %}
        <p class="text-slate-800 mb-4">
            <strong>Descripción: </strong><br>
            {{ item.description }}
        </p>
        {% endif %}
        {% if request.user.is_authenticated %}
            {% if not request.user.vendedor %}
                <a href="{% url 'item:add_to_cart' item.id%}" class="inline-block mt-6 px-6 py-3 text-lg text-white bg-slate-600 rounded-xl hover:bg-slate-500 transition-colors duration-300">Agregar al carrito</a>
            {% endif %}
        {% endif %}    
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-slate-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Productos Relacionados</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href= "{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" alt="item" class="w-full h-80 object-cover rounded-xl">
                    </div>

                    <div class="p-6 bg-white rounded-xl">
                        <h2 class="mb-2 text-2xl">{{ item.name }}</h2>
                        <p class="mb-2 text-slate-600">{{ item.description }}</p>
                        <p class="text-slate-900 font-bold">Precio: {{ item.price }} $</p>
                    </div>
                </a> 
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

item/templates/item/edit_item.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="container mx-auto px-6 py-8">
    <h1 class="block text-gray-700 text-2xl font-bold mb-2 text-center"> Editar producto </h1>
    
    <form method="post" action="." enctype="multipart/form-data" class="w-full max-w-lg mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4 space-y-4">
            {% for field in form %}
                <div>
                    <label for="{{ field.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                        {{ field.label }}
                    </label>
                    {{ field|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
                    {% if field.help_text %}
                        <p class="text-gray-500 text-xs italic">{{ field.help_text }}</p>
                    {% endif %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <p class="text-red-500 text-xs italic">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        {% if form.non_field_errors %}
            <div class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <strong class="font-bold">Error:</strong>
                <span class="block sm:inline">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </span>
            </div>
        {% endif %}

        <div class="flex items-center justify-center">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" style="transition: background-color .15s ease">
                Enviar
            </button>
        </div>
    </form>
</div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="container mx-auto px-6 py-8">
    <h1 class="block text-gray-700 text-2xl font-bold mb-2 text-center"> Agregar un nuevo producto </h1>
    
    <form method="post" action="." enctype="multipart/form-data" class="w-full max-w-lg mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4 space-y-4">
            {% for field in form %}
                <div>
                    <label for="{{ field.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                        {{ field.label }}
                    </label>
                    {{ field|add_class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" }}
                    {% if field.help_text %}
                        <p class="text-gray-500 text-xs italic">{{ field.help_text }}</p>
                    {% endif %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <p class="text-red-500 text-xs italic">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        {% if form.non_field_errors %}
            <div class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <strong class="font-bold">Error:</strong>
                <span class="block sm:inline">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </span>
            </div>
        {% endif %}

        <div class="flex items-center justify-center">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" style="transition: background-color .15s ease">
                Enviar
            </button>
        </div>
    </form>
</div>
{% endblock %}

item/templates/item/search.html
{% extends 'core/base.html' %}

{% block title %}Resultados de busqueda: "{{query}}"{% endblock %}

{% block content %}
    <h1 class="text-2xl">Resultados de busqueda: "{{query}}"</h1>

    <div class="flex justify-end mb-4">
        <form id="searchForm" method="get" action="{% url 'item:search' %}">
            <input type="hidden" name="query" value="{{ query }}">
            <label for="sort">Ordenar por precio:</label>
            <select id="sort" name="sort" onchange="submitForm()">
                <option value="">Seleccionar</option>
                <option value="asc" {% if request.GET.sort == 'asc' %}selected{% endif %}>Ascendente</option>
                <option value="desc" {% if request.GET.sort == 'desc' %}selected{% endif %}>Descendente</option>
            </select>
        </form>
    </div>

    <div class="flex flex-wrap gap-2">
        {% if item %}
            {% for i in item %}
                <div>
                    <a href= "{% url 'item:detail' i.id %}">
                        <div>
                            <img src="{{ i.image.url }}" alt="item" class="w-full h-80 object-cover rounded-xl">
                        </div>

                        <div class="p-6 bg-white rounded-xl">
                            <h2 class="mb-2 text-2xl">{{ i.name }}</h2>
                            <p class="mb-2 text-gray-600">{{ i.description }}</p>
                            <p class="text-gray-900 font-bold">Price: {{ i.price }} $</p>
                        </div>
                    </a> 
                </div>
            {% endfor %}
        {% else %}
        <div class="w-full p-2">
            <p class="text-xl text-slate-800">No se encontraron productos relacionados a tu busqueda:"{{query}}".</p>
        </div>
        {% endif %}
    </div>

    {% if item.has_other_pages %}
      <div class="pagination">
        {% if item.has_previous %}
          <a href="?query={{ query }}&page={{ item.previous_page_number }}">anterior</a>
        {% endif %}
        
        <span class="current-page">{{ item.number }}</span>
        
        {% if item.has_next %}
          <a href="?query={{ query }}&page={{ item.next_page_number }}">siguiente</a>
        {% endif %}
      </div>
    {% endif %}

    <script>
        function submitForm() {
            document.getElementById("searchForm").submit();
        }
    </script>
{% endblock %}