core/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.frontpage, name='home'),
    path('terms/', views.terms, name='terms'),
]

item/urls.py
from django.urls import path

from . import views

# Definimos el nombre de la aplicación, que se usará para hacer referencia a estas URLs desde otras partes de Django
app_name = 'item'

# Definimos las URLs para esta aplicación
urlpatterns = [
    # La URL 'new/' está asociada con la vista 'new'. Esto significa que cuando un usuario visita 'item/new/', Django ejecutará la función de vista 'new'.
    path('new/', views.new, name='new'),
    path('add-to-cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('increase-quantity/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease-quantity/<int:item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('cart/', views.cart_view, name='cart_view'),
    # La URL '<int:pk>/' está asociada con la vista 'detail'. Esto significa que cuando un usuario visita 'item/1/', por ejemplo, Django ejecutará la función de vista 'detail' con 'pk' igual a 1.
    path('<int:pk>/', views.detail, name='detail'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('<int:pk>/edit/', views.edit_item, name='edit'),
    path('<int:pk>/delete/', views.delete_item, name='delete'),
    path('search/', views.search, name='search'),
    path('category/<int:pk>/', views.category_detail, name='category_detail'),
    
]

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'  

urlpatterns = [
    path('resumen/', views.resumen_pedido, name='resumen_pedido'),
    path('confirmar/', views.confirmar_compra, name='confirmar_compra'),
    path('cancelar/', views.cancelar_compra, name='cancelar_compra'),
    path('historial_vendedor/', views.historial_pedidos_vendedor, name='historial_pedidos_vendedor'),
    path('historial/', views.historial_pedidos, name='historial_pedidos'),
    path('actualizar/<int:pedido_id>/', views.actualizar_estado_pedido, name='actualizar_estado'),
    
]

puracultura/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('pedido/', include('pedido.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/models.py
from django.db import models
from django.conf import settings
from item.models import Item
from userprofile.models import Direccion

class Pedido(models.Model):
    ESTADO_OPCIONES = [
        ('en proceso', 'En Proceso'),
        ('enviado', 'Enviado'),
        ('entregado', 'Entregado'),
    ]

    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    actualizacion = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=20, choices=ESTADO_OPCIONES, default='en proceso')
    costo_total = models.FloatField()
    direccion_envio = models.ForeignKey(Direccion, on_delete=models.SET_NULL, null=True)
    

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Item, on_delete=models.CASCADE)
    precio = models.FloatField()
    cantidad = models.IntegerField()
    
    

pedido/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Pedido, ItemPedido, Direccion, Item
from item.cart import Cart
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import F 

@login_required
def resumen_pedido(request):
    cart = Cart(request)
    direcciones = Direccion.objects.filter(usuario=request.user)
    if request.method == 'POST':
        direccion_id = request.POST.get('direccion')
        direccion = get_object_or_404(Direccion, id=direccion_id)
        return render(request, 'confirmar_pedido.html', {
            'cart': cart,
            'IVA': cart.get_IVA(),
            'direccion': direccion,
        })
    else:
        return render(request, 'pedido/resumen_pedido.html', {
            'cart': cart,
            'direcciones': direcciones,
        })

@login_required
def confirmar_compra(request):
    cart = Cart(request)
    if request.method == 'POST':
        direccion_id = request.POST.get('direccion')
        direccion = get_object_or_404(Direccion, id=direccion_id)

        # Initialize a dictionary to hold orders by vendor
        orders_by_vendor = {}

        # Iterate over items in the cart
        for item_id, item_data in cart.cart.items():
            item = Item.objects.get(id=item_id)
            vendor_id = item.created_by.id

            # Add the item to the vendor's order
            if vendor_id not in orders_by_vendor:
                orders_by_vendor[vendor_id] = {
                    'pedido': None,
                    'items': [],
                    'total': 0
                }

            orders_by_vendor[vendor_id]['items'].append(item)
            orders_by_vendor[vendor_id]['total'] += item.price * item_data['quantity']

        # Create an order for each vendor
        for vendor_id, data in orders_by_vendor.items():
            pedido = Pedido.objects.create(
                usuario=request.user,
                estado='En proceso',
                costo_total=data['total'],
                direccion_envio=direccion
            )
            data['pedido'] = pedido

            # Create an ItemPedido for each item
            for item in data['items']:
                quantity = cart.cart[str(item.id)]['quantity']
                ItemPedido.objects.create(
                    pedido=pedido,
                    producto=item,
                    precio=item.price,
                    cantidad=quantity,
                )
                # Update stock
                item.stock -= quantity
                item.save()

        cart.clear()
        return redirect('core:home')
    else:
        return redirect('item:cart_view')


@login_required
def cancelar_compra(request):
    return redirect('item:cart_view')

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Pedido, ItemPedido, Direccion, Item
from item.cart import Cart
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

@login_required
def resumen_pedido(request):
    cart = Cart(request)
    direcciones = Direccion.objects.filter(usuario=request.user)
    if request.method == 'POST':
        direccion_id = request.POST.get('direccion')
        direccion = get_object_or_404(Direccion, id=direccion_id)
        return render(request, 'confirmar_pedido.html', {
            'cart': cart,
            'IVA': cart.get_IVA(),
            'direccion': direccion,
        })
    else:
        return render(request, 'pedido/resumen_pedido.html', {
            'cart': cart,
            'direcciones': direcciones,
        })

@login_required
def confirmar_compra(request):
    cart = Cart(request)
    if request.method == 'POST':
        direccion_id = request.POST.get('direccion')
        direccion = get_object_or_404(Direccion, id=direccion_id)

        # Initialize a dictionary to hold orders by vendor
        orders_by_vendor = {}

        # Iterate over items in the cart
        for item_id, item_data in cart.cart.items():
            item = Item.objects.get(id=item_id)
            vendor_id = item.created_by.id

            # Add the item to the vendor's order
            if vendor_id not in orders_by_vendor:
                orders_by_vendor[vendor_id] = {
                    'pedido': None,
                    'items': [],
                    'total': 0
                }

            orders_by_vendor[vendor_id]['items'].append(item)
            orders_by_vendor[vendor_id]['total'] += item.price * item_data['quantity']

        # Create an order for each vendor
        for vendor_id, data in orders_by_vendor.items():
            pedido = Pedido.objects.create(
                usuario=request.user,
                estado='En proceso',
                costo_total=data['total'],
                direccion_envio=direccion
            )
            data['pedido'] = pedido

            # Create an ItemPedido for each item
            for item in data['items']:
                quantity = cart.cart[str(item.id)]['quantity']
                ItemPedido.objects.create(
                    pedido=pedido,
                    producto=item,
                    precio=item.price,
                    cantidad=quantity,
                )
                # Update stock
                item.stock -= quantity
                item.save()

        cart.clear()
        return redirect('core:home')
    else:
        return redirect('item:cart_view')

@login_required
def cancelar_compra(request):
    return redirect('item:cart_view')

@login_required
def historial_pedidos(request):
    pedidos = Pedido.objects.filter(usuario=request.user).annotate(
        vendedor_name=F('itempedido__producto__created_by__username')
    ).order_by('-fecha_creacion')
    
    paginator = Paginator(pedidos, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'pedido/historial_pedidos.html', {'page_obj': page_obj})


@login_required
def historial_pedidos_vendedor(request):
    pedidos_vendedor = Pedido.objects.filter(
        itempedido__producto__created_by=request.user
    ).distinct().order_by('-fecha_creacion')

    paginator = Paginator(pedidos_vendedor, 10)  
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'pedido/historial_pedidos_vendedor.html', {'page_obj': page_obj})

@login_required
def actualizar_estado_pedido(request, pedido_id):
    pedido = Pedido.objects.get(id=pedido_id)
    if request.method == 'POST' and pedido.itempedido_set.first().producto.created_by == request.user:
        nuevo_estado = request.POST.get('estado')
        pedido.estado = nuevo_estado
        pedido.save()
    return HttpResponseRedirect(reverse('pedido:historial_pedidos_vendedor'))

pedido/templates/pedido/historial_pedidos.html
{% extends 'core/base.html' %}

{% block title %}Mis Pedidos{% endblock %}

{% block content %}
<div class="container mx-auto mt-10 mb-10">
    <h2 class="text-3xl font-semibold mb-5">Historial de Pedidos</h2>
    {% if page_obj %}
        <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="py-3 px-6">Pedido ID</th>
                        <th scope="col" class="py-3 px-6">Vendedor</th>
                        <th scope="col" class="py-3 px-6">Fecha</th>
                        <th scope="col" class="py-3 px-6">Estado</th>
                        <th scope="col" class="py-3 px-6">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pedido in page_obj %}
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                            <td class="py-4 px-6">{{ pedido.id }}</td>
                            <td class="py-4 px-6">{{ pedido.vendedor_name }}</td>
                            <td class="py-4 px-6">{{ pedido.fecha_creacion }}</td>
                            <td class="py-4 px-6">{{ pedido.estado }}</td>
                            <td class="py-4 px-6">${{ pedido.costo_total }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="bg-white shadow-md rounded my-6 p-6">
            No has realizado pedidos aún.
        </div>
    {% endif %}
    <div class="mt-4">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="mr-2">Anterior</a>
        {% endif %}
        Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="ml-2">Siguiente</a>
        {% endif %}
    </div>
</div>
{% endblock %}

pedido/templates/pedido/historial_pedidos_vendedor.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mx-auto p-6">
    <h2 class="text-2xl font-bold mb-4">Historial de Pedidos</h2>
    <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="py-3 px-6">Pedido ID</th>
                    <th scope="col" class="py-3 px-6">Estado</th>
                    <th scope="col" class="py-3 px-6">Acciones</th>
                    <th scope="col" class="py-3 px-6">Direccion</th>
                    <th scope="col" class="py-3 px-6">Precio Total</th>
                </tr>
            </thead>
            <tbody>
                {% for pedido in page_obj %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <td class="py-4 px-6">{{ pedido.id }}</td>
                        <td class="py-4 px-6">{{ pedido.estado }}</td>
                        <td class="py-4 px-6">
                            <form method="post" action="{% url 'pedido:actualizar_estado' pedido.id %}">
                                {% csrf_token %}
                                <select name="estado" class="bg-gray-50 border border-gray-300 p-2 rounded">
                                    <option value="en proceso" {% if pedido.estado == 'en proceso' %}selected{% endif %}>En Proceso</option>
                                    <option value="enviado" {% if pedido.estado == 'enviado' %}selected{% endif %}>Enviado</option>
                                    <option value="entregado" {% if pedido.estado == 'entregado' %}selected{% endif %}>Entregado</option>
                                </select>
                                <button type="submit" class="ml-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                                    Actualizar Estado
                                </button>
                            </form>
                        </td>
                        <td class="py-4 px-6">{{ pedido.direccion_envio }}</td>
                        <td class="py-4 px-6">{{ pedido.costo_total }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}
        Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        {% endif %}
    </div>
{% endblock %}

pedido/templates/pedido/resumen_pedido.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mx-auto p-6">
    <h2 class="text-2xl font-bold mb-4">Resumen del Pedido</h2>
    <form method="post" action="{% url 'pedido:confirmar_compra' %}">
        {% csrf_token %}
        <div class="mb-6">
            <label for="direccion" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Elige tu dirección de envío:</label>
            <select id="direccion" name="direccion" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                {% for direccion in direcciones %}
                    <option value="{{ direccion.id }}">{{ direccion.direccion }}, {{ direccion.ciudad }}, {{ direccion.pais }}</option>
                {% endfor %}
            </select>
        </div>
        <!-- Resumen del Carrito -->
        <div class="mb-6">
            {% for item in cart %}
            <div class="flex justify-between mb-2">
                <span>{{ item.product.name }} (x{{ item.quantity }})</span>
                <span>${{ item.product.price }}</span>
            </div>
            {% endfor %}
        </div>

        <!-- IVA y Costo Total -->
        <div class="mb-6">
            <div class="flex justify-between mb-2">
                <span>Subtotal:</span>
                <span>${{ cart.get_subtotal }}</span>
            </div>
            <div class="flex justify-between mb-2">
                <span>IVA (13%):</span>
                <span>${{ cart.get_iva }}</span>
            </div>
            <div class="flex justify-between">
                <strong>Total:</strong>
                <strong>${{ cart.get_total_cost }}</strong>
            </div>
        </div>
        
        <div class="flex justify-between items-center">
            <button type="submit" class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Confirmar Compra</button>
            <a href="{% url 'item:cart_view' %}" class="bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Cancelar y volver al carrito</a>
        </div>
    </form>
</div>
{% endblock %}